# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ed15320cac0d16b8a3607a5d67db9a5dde8691037c0f8be2ea900116aae6f977a2bfc82ccfc86dab65b2c4c0d82f6ab16e63674b2605a5a3c88ea0d2e517222

test:
  secret_key_base: 15f77819ae6994996defc70781a097b32318993850849319b89eca88412d0c9be1dad87b35857f2b4f5e4f321c0c960a3cf141c7cef9749c4e980cae182629fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
